// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SearchBarController from "./search_bar_controller"
application.register("search-bar", SearchBarController)

import BookingFormController from "./booking_form_controller"
application.register("booking-form", BookingFormController)

import MapRequestController from "./map_controller"
application.register("map", MapRequestController)